import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iranSans = localFont({
  src: [{ path: "./fonts/iran-sans/IRANSansXV.woff", weight: "500", style: "normal" }],
  variable: "--font-iran-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    fontFamily: "var(--font-iran-sans), sans-serif",
  });
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${iranSans.variable} h-full scroll-smooth antialiased`}
      suppressHydrationWarning
    >
      <head suppressHydrationWarning>
        <ColorSchemeScript forceColorScheme="light" />
      </head>
      <body className="flex min-h-full flex-col">
        <MantineProvider theme={theme} forceColorScheme="light">
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
